### ISSUE TITLE
[앱 추가 기능]현재 send된 데이터 수의 확인 작업

### ISSUE THREAD

**Issue by Taeho24** [marmot8080/POST_OpenSourcePrj#18]
현재 send된 데이터의 수를 확인하기 위해서 다른 인터넷 브라우저에서 url을 통해 확인하는 방법이 번거롭다고 느꼈습니다.
이에 따라 url의 데이터를 크롤링을 통해서 앱에서 자체적으로 볼 수 있도록 기능을 추가하는 것을 제안합니다.

**Comment by marmot8080** [comment]
좀 더 조사해보긴 해야겠지만 가능할 것 같습니다.
화면구성 및 레이아웃 관련해서도 의견 있으시면 말씀해주시면 감사하겠습니다.

**Comment by Taeho24** [comment]
현재 Dev/v0.2와 별개로 Dev/v0.3 branch로 따로 만들어보겠습니다

**Comment by Taeho24** [comment]
브랜치명을 Dev/v0.3 Dev/v0.22로 바꿔서 개발하겠습니다

**Comment by Taeho24** [comment]
Dev/v0.3에는 기존의 기능을 추가하는 것으로 하고
Dev/v와는 별개로 siteData_crawling 라는 이름의 브랜치로 따로 분리해서만들겠습니다.

**Comment by marmot8080** [comment]
siteData_crawling -> Feature/server-crawling 으로 branch명 변경했습니다.

**Comment by Taeho24** [comment]
#23 Feature development completed
