### ISSUE TITLE
exception: 페어링 상태일 경우 페어링 시도 예외처리

### ISSUE THREAD

**Issue by marmot8080** [marmot8080/POST_OpenSourcePrj#25]
이미 페어링된 기기가 존재할 경우 검색되는 기기와의 페어링 연결을 시도할 경우 에러가 발생한다고 합니다.
이러한 경우를 사전에 차단하기 위한 예외처리가 필요할 것 같습니다.
일단 제가 생각했을 때는 어떤 한 기기와 연결하게될 경우 connectedThread를 생성하여 활용하기 때문에 .getState()를 이용해서 반환되는 현재 스레드의 상태를 통해 페어링된 기기가 존재하는지 여부를 확인하는 방법도 가능할 거라고 생각됩니다.
하지만 아직 생성되지 않았을 경우의 스레드 상태는 어떻게 반환되는지 확인해보지 않아 이 부분에서 문제가 발생할 가능성도 있을 것 같습니다.
만약 그럴 경우 ConnectedThread에 static의 boolean 변수를 선언하여 활용하는 방법도 있을 것 같습니다.
혹시 다른 아이디어가 있으시다면 말씀해주시면 감사하겠습니다.

**Comment by marmot8080** [comment]
생각해보니 이미 연결된 기기와 다시 연결을 시도할 경우에만 예외로 처리하고, 페어링 상태일 때 다른 기기와의 페어링을 시도하는 경우에는 현재 연결된 기기의 연결을 끊고 다른 기기와 연결을 시도하는 방식으로 하는 편이 좋을 것 같네요.

**Comment by marmot8080** [comment]
확인해본 결과 생성되지 않은 스레드 객체는 .getState()를 했을 때 오류가 발생했기 때문에 connectedThread = null;로 초기화하여 사용할 수 있을 것 같습니다.

또한, ConnectedThread 클래스에 connectedDevice 이런 변수를 생성해서 현재 페어링 중인 디바이스를 확인할 수 있도록 하는 방법도 좋을 것 같습니다.

**Comment by Taeho24** [comment]
페어링 시도 시 새로운 패어링 기기와 현재 페어링된 연결 기기와의 우선 순위를 정하여 처리하는 것이 좋을 것 같습니다.

> 생각해보니 이미 연결된 기기와 다시 연결을 시도할 경우에만 예외로 처리하고, 페어링 상태일 때 다른 기기와의 페어링을 시도하는 경우에는 현재 연결된 기기의 연결을 끊고 다른 기기와 연결을 시도하는 방식으로 하는 편이 좋을 것 같네요.

**Comment by marmot8080** [comment]
우선순위에 따라서 어떤 차이를 두고 작업을 처리하시려는 계획이신가요?

**Comment by Taeho24** [comment]
현재 문제가 되는 부분이 이미 페어링된 기기가 존재할 경우 검색되는 기기와의 페어링 연결을 시도할 경우 에러가 발생하는 것이라면 경우가 2가지가 있다고 생각하였습니다.

경우1. 같은 기기에서 이미 페어링된 후 다시 페어링 시도를 하는 경우

경우2. 다른 두 기기에서 첫 번째 기기에서 페어링된 상태에서 두 번째 기기에서 페어링을 시도하는 경우

두 경우 모두 페어링의 우선 순위를 처리하는 부분에 오류가 있어 에러가 발생한다고 생각합니다.

이에 따른 처리 방법으로 우선순위를 두어
처리 방법1. 기존의 페어링을 유지한 후 새로운 페어링 시도를 거부하고 페어링에 대한 time을 따로 걸어 처리하는 방법
처리 방법2. 기존의 페어링을 끊고 새로운 페어링을 연결한 후 기존의 페어링 기기에 끊김 신호를 보내는 방법

을 생각 중인데, 현재 처리 방법 2를 생각하고계신건가요?

**Comment by marmot8080** [comment]
라즈베리 파이에서의 예외처리를 말씀하신 거였네요.
그럼 라즈베리 파이에서의 예외처리를 맡아주시면 제가 안드로이드 앱 부분에서의 예외처리를 추가하도록 하겠습니다.
