### ISSUE TITLE
update: bluetooth scan을 on/off 형태로 설정 가능하도록 변경

### ISSUE THREAD

**Issue by marmot8080** [marmot8080/POST_OpenSourcePrj#9]
토글 버튼을 추가해서 bluetooth scan을 on/off 설정 가능하도록 변경했습니다.
또한 그에 따라 스캔 중 OTP를 읽어왔을 경우 팝업 메시지를 통해 POST 요청을 보낼지 묻는 방식으로 수정했습니다.
기본 틀은 만들어놨지만 디자인적으로는 부족하니 디자인 부분에서 다른 분이 수정해주셨으면 좋겠습니다.

**Comment by Bakhyoungwoo** [comment]
네 알겠습니다
